import { Container, getContainer } from "@cloudflare/containers";
import {
  WorkflowEntrypoint,
  type WorkflowEvent,
  type WorkflowStep,
} from "cloudflare:workers";
import { createPrismaForD1 } from "../lib/prisma";
import type {
  CloudflareEnv,
  ProcessorResult,
  TranscriptionWorkflowParams,
} from "../lib/cloudflare-types";

// @ts-ignore .open-next/worker.js is generated by opennextjs-cloudflare build.
import nextHandler from "../.open-next/worker.js";

export { ContainerProxy } from "@cloudflare/containers";

export class MediaProcessorContainer extends Container<CloudflareEnv> {
  defaultPort = 8080;
  sleepAfter = "10m";
  pingEndpoint = "container/health";

  constructor(ctx: DurableObjectState<{}>, env: CloudflareEnv) {
    super(ctx, env);
    this.envVars = {
      GROQ_API_KEY: env.GROQ_API_KEY ?? "",
      GROQ_TEXT_MODEL: env.GROQ_TEXT_MODEL ?? "llama-3.1-8b-instant",
    };
  }
}


export class TranscriptionWorkflow extends WorkflowEntrypoint<
  CloudflareEnv,
  TranscriptionWorkflowParams
> {
  async run(event: WorkflowEvent<TranscriptionWorkflowParams>, step: WorkflowStep) {
    const payload = event.payload;

    try {
      await step.do("mark transcription as processing", async () => {
        const prisma = createPrismaForD1(this.env.DB);
        try {
          await prisma.transcription.update({
            where: { id: payload.transcriptionId },
            data: { status: "processing", errorMessage: null },
          });
        } finally {
          await prisma.$disconnect();
        }
      });

      const result = await step.do(
        "process media in container",
        {
          retries: { limit: 2, delay: "30 seconds", backoff: "exponential" },
          timeout: "2 hours",
        },
        async () => {
          const container = getContainer(this.env.MEDIA_PROCESSOR, payload.transcriptionId);
          const response = await container.containerFetch(
            "http://media.local/process",
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                ...payload,
                r2BaseUrl: "http://host.docker.internal:8787/api/media-download",
                groqApiKey: this.env.GROQ_API_KEY,
              }),
            }
          );

          if (!response.ok) {
            throw new Error(await response.text());
          }

          return (await response.json()) as ProcessorResult;
        }
      );

      await step.do("persist transcription result", async () => {
        const prisma = createPrismaForD1(this.env.DB);
        try {
          await prisma.transcription.update({
            where: { id: payload.transcriptionId },
            data: {
              status: "completed",
              transcriptText: result.text,
              summaryText: result.summary,
              durationSeconds: result.durationSeconds,
              errorMessage: null,
            },
          });

          if (result.dalils.length > 0) {
            await prisma.dalil.createMany({
              data: result.dalils.map((dalil) => ({
                transcriptionId: payload.transcriptionId,
                type: dalil.type,
                reference: dalil.reference,
                textAr: dalil.text_ar ?? null,
                textId: dalil.text_id ?? null,
                confidence: dalil.confidence ?? 0,
              })),
            });
          }

          const durationMinutes = Math.max(1, Math.ceil(result.durationSeconds / 60));
          await prisma.user.update({
            where: { id: payload.userId },
            data: { quotaMinutes: { decrement: durationMinutes } },
          });
        } finally {
          await prisma.$disconnect();
        }
      });

      if (payload.sourceObjectKey) {
        await step.do("delete source object", async () => {
          await this.env.MEDIA_BUCKET.delete(payload.sourceObjectKey!);
        });
      }

      return { transcriptionId: payload.transcriptionId, status: "completed" };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      await step.do("mark transcription as failed", async () => {
        const prisma = createPrismaForD1(this.env.DB);
        try {
          await prisma.transcription.update({
            where: { id: payload.transcriptionId },
            data: { status: "failed", errorMessage: message },
          });
        } finally {
          await prisma.$disconnect();
        }
      });
      throw error;
    }
  }
}

export default {
  fetch: nextHandler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
